server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@10.170.1.182:8761/eureka
  server:
    enable-self-preservation: false #关闭自我保护
security:
  user:
    password: admin
    name: admin

